[DEFAULT]
# the default branch for upstream sources:
upstream-branch = upstream-experimental
# the default branch for the debian patch:
debian-branch = suites/unstable
# Don't use pristine-tar:
pristine-tar = False

debian-tag = devuan/%(version)s
