[DEFAULT]
# the default branch for upstream sources:
upstream-branch = upstream-experimental
# the default branch for the debian patch:
debian-branch = suites/experimental
# use pristine-tar:
pristine-tar = False

